#pragma once

#define DEBUG_SAVE_VAR_IMS 1
#define DEBUG_SAVE_IDEPTH_IMS 0
#define DEBUG_SAVE_MATCH_IMS 0
#define DEBUG_SAVE_SEARCH_RANGE_IMS 0
#define DEBUG_SAVE_RESULT_IMS 1
#define DEBUG_SAVE_PIXEL_DISPARITY_IMS 0
#define DEBUG_SAVE_FRAME_POINT_CLOUDS 1
#define DEBUG_SAVE_KEYFRAME_PROPAGATION_CLOUDS 1
